### ISSUE TITLE
What's operating system this script used?

### ISSUE THREAD

**Issue by lygstate** [tilezen/osm2pgsql-ec2#1]
I want to creating an offline version of this.

**Comment by nvkelso** [comment]
@lygstate We test both Ubuntu (14.04) and on Mac.

See also:

- https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service

**Comment by lygstate** [comment]
@nvkelso I means the ec2 instance also using Ubuntu 14.04? or other versions.

**Comment by nvkelso** [comment]
Yes, 14.04.

**Comment by nvkelso** [comment]
Yes, even the ec2
